### ISSUE TITLE
New version does not work with Klarna

### ISSUE THREAD

**Issue by Trustedbrands** [Dintero/Dintero.Checkout.WooCommerce#23]
Does not work with Klarna Checkout. If a customer wants to pay with Klarna, Klarna checkout does not load.
![Klarna-fail](https://user-images.githubusercontent.com/69647853/105847412-e0de2c80-5fdd-11eb-820b-1c415c19bbc2.JPG)

**Comment by frodeaa** [comment]
close, plugin have been deprecated, use https://github.com/Dintero/Dintero.Checkout.WooCommerce.V2
