### ISSUE TITLE
Use built-in shipping options

### ISSUE THREAD

**Issue by andersem** [Dintero/Dintero.Checkout.WooCommerce#5]
For updating shipping options, the plugin uses `lockSession - updateSession - refreshSession`. This process is expensive, and is really built for updating the items on the order. Customers are complaining about the high round trip time.

If the intention is to update the shipping options, there's a better way:

Every time the customers shipping address is updated in the checkout, a callback will be sent to the url configured in the session at `express.shipping_address_callback_url`, documented here: https://docs.dintero.com/checkout-api.html#operation/checkout_session_post. The response from this request, should contain the new valid shipping options:

Example:
```json
{
  "shipping_options": [
    {
      "id": "bring-pick-up-00001",
      "line_id": "bring-pick-up-00001-location-0a1f6b",
      "country": "NO",
      "amount": 3900,
      "vat_amount": 975,
      "vat": 25,
      "title": "Standard",
      "description": "Pick up at your nearest postal office",
      "delivery_method": "pick_up",
      "operator": "Bring",
      "operator_product_id": "pick-up-00001-location-0a1f6b",
      "eta": {
        "relative": {
          "minutes_min": 0,
          "minutes_max": 0
        },
        "absolute": {
          "starts_at": "2020-10-14T19:00:00Z",
          "ends_at": "2020-10-14T20:00:00Z"
        }
      },
      "time_slot": {
        "starts_at": "2020-10-14T19:00:00Z",
        "ends_at": "2020-10-14T20:00:00Z"
      },
      "pick_up_address": {
        "first_name": "John",
        "last_name": "Doe",
        "address_line": "string",
        "address_line_2": "string",
        "co_address": "Land Lord",
        "business_name": "string",
        "postal_code": "O349",
        "postal_place": "Oslo",
        "country": "NO",
        "phone_number": "string",
        "email": "string",
        "latitude": 0,
        "longitude": 0,
        "comment": "string"
      }
    }
  ]
}
``` 

This should be the default way of updating shipping options. If it makes sense, maybe doing it from the outside can be an option.

**Comment by andersem** [comment]
After discussions, we've concluded that some shipping operators have complex structures that it's hard to support in the checkout.

**Comment by frodeaa** [comment]
not sure if I understand why the plugin can support the current flow but not supporting the `express.shipping_address_callback_url`, it updates the session with new shipping option...

**Comment by andersem** [comment]
Callback url can be used, that's no problem, but adapting the models of all the shipping providers is hard.

One example is Porterbuddy, where you can tick a box and write comments to the messenger.
![image](https://user-images.githubusercontent.com/509817/98092349-d8ff6800-1e86-11eb-8c53-a16c414e9c73.png)

**Comment by frodeaa** [comment]
close, the callback option for shipping options is not recommended by our new plugin
