### ISSUE TITLE
Support new async operations

### ISSUE THREAD

**Issue by daronm** [Dintero/Dintero.Checkout.WooCommerce#7]
- capture/refund will be async operations for some transaction, the response will state that by having an INITIATE_REFUND or INITIATE_CAPTURE event.
- a callback to the callback_url will be supported, to receive a callback when the transaction is updated with CAPTURE or REFUND event
Callback when the transaction is updated can be enabled by including report_event=CAPTURE&report_event=REFUND in the callback_url set when creating the session. The callback received should then be used to update the payment status on the order

**Comment by frodeaa** [comment]
close, plugin have been deprecated, use https://github.com/Dintero/Dintero.Checkout.WooCommerce.V2
