### ISSUE TITLE
Order with status `on-hold` is changed before transaction is authorized

### ISSUE THREAD

**Issue by frodeaa** [Dintero/Dintero.Checkout.WooCommerce#71]
We have an order with following order status history

 - pending
 - on-hold
 - processing
 - failed

The order should not have change status from on-hold to `processing` as the payment transaction had still status `ON_HOLD`.

The Dintero API logs shows that WooCommerce fetched the transaction details before the order changed status...

Rel: https://github.com/Dintero/Dintero.Checkout.WooCommerce/pull/70

**Comment by andersem** [comment]
Closed by #70
